{
    "CVE-ID": "CVE-2010-3492",
    "NVD": {
        "Descriptions": "The asyncore module in Python before 3.2 does not properly handle unsuccessful calls to the accept function, and does not have accompanying documentation describing how daemon applications should handle unsuccessful calls to the accept function, which makes it easier for remote attackers to conduct denial of service attacks that terminate these applications via network connections.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 0,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "2.7"
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.0",
                "VersionEndExcluding": "3.1.2",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.1.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.1/Misc/NEWS"
            ],
            "BTS": {
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.2a3": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.7.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.1rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}