{
    "CVE-ID": "CVE-2013-1752",
    "Official": {
        "2.6.9rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.6/Misc/NEWS"
            ],
            "BTS": {
                "16042": {
                    "ID": "16042",
                    "url": "https://bugs.python.org/issue16042"
                }
            }
        },
        "3.2.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "16040": {
                    "ID": "16040",
                    "url": "https://bugs.python.org/issue16040"
                }
            }
        },
        "3.4.0b1": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/HISTORY",
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.0b1.rst"
            ],
            "BTS": {
                "16040": {
                    "ID": "16040",
                    "url": "https://bugs.python.org/issue16040",
                    "date": "8967",
                    "nonce": "xg3xlX",
                    "section": "Library"
                },
                "16041": {
                    "ID": "16041",
                    "url": "https://bugs.python.org/issue16041",
                    "date": "8966",
                    "nonce": "XFY0lr",
                    "section": "Library"
                },
                "16039": {
                    "ID": "16039",
                    "url": "https://bugs.python.org/issue16039",
                    "date": "8964",
                    "nonce": "ipafYi",
                    "section": "Library"
                },
                "16038": {
                    "ID": "16038",
                    "url": "https://bugs.python.org/issue16038",
                    "date": "8938",
                    "nonce": "TZGbSo",
                    "section": "Library"
                }
            }
        },
        "2.7.6rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.6rc1/Misc/NEWS",
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.6rc1.rst"
            ],
            "BTS": {
                "16038": {
                    "ID": "16038",
                    "url": "https://bugs.python.org/issue16038",
                    "date": "9166",
                    "nonce": "TZGbSo",
                    "section": "Library"
                },
                "16040": {
                    "ID": "16040",
                    "url": "https://bugs.python.org/issue16040",
                    "date": "9158",
                    "nonce": "xg3xlX",
                    "section": "Library"
                }
            }
        },
        "2.7.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.7rc1/Misc/NEWS",
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.7rc1.rst"
            ],
            "BTS": {
                "16039": {
                    "ID": "16039",
                    "url": "https://bugs.python.org/issue16039",
                    "date": "9267",
                    "nonce": "Cy3_BL",
                    "section": "Library"
                }
            }
        },
        "2.7.9": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.9/Misc/NEWS",
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.9.rst"
            ],
            "BTS": {
                "16042": {
                    "ID": "16042",
                    "url": "https://bugs.python.org/issue16042",
                    "date": "9492",
                    "nonce": "7I3FPy",
                    "section": "Library"
                },
                "16041": {
                    "ID": "16041",
                    "url": "https://bugs.python.org/issue16041",
                    "date": "9491",
                    "nonce": "TyhfVi",
                    "section": "Library"
                }
            }
        },
        "3.3.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.3.3rc1/Misc/NEWS",
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.3rc1.rst"
            ],
            "BTS": {
                "16040": {
                    "ID": "16040",
                    "url": "https://bugs.python.org/issue16040",
                    "date": "9741",
                    "nonce": "xg3xlX",
                    "section": "Library"
                },
                "16041": {
                    "ID": "16041",
                    "url": "https://bugs.python.org/issue16041",
                    "date": "9740",
                    "nonce": "XFY0lr",
                    "section": "Library"
                },
                "16039": {
                    "ID": "16039",
                    "url": "https://bugs.python.org/issue16039",
                    "date": "9738",
                    "nonce": "ipafYi",
                    "section": "Library"
                },
                "16038": {
                    "ID": "16038",
                    "url": "https://bugs.python.org/issue16038",
                    "date": "9728",
                    "nonce": "TZGbSo",
                    "section": "Library"
                }
            }
        },
        "3.3.4rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.3.4rc1/Misc/NEWS",
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.4rc1.rst"
            ],
            "BTS": {
                "16042": {
                    "ID": "16042",
                    "url": "https://bugs.python.org/issue16042",
                    "date": "9884",
                    "nonce": "Hj_jQP",
                    "section": "Library"
                }
            }
        },
        "2.7.16rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.16rc1.rst"
            ],
            "BTS": {
                "16039": {
                    "ID": "16039",
                    "url": "https://bugs.python.org/issue16039",
                    "date": "2018-12-11-16-00-57",
                    "nonce": "PCj2n4",
                    "section": "Security"
                }
            }
        }
    }
}