{
    "CVE-ID": "CVE-2020-15801",
    "NVD": {
        "Descriptions": "In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
        "Cvss2_BaseScore": 7.5,
        "Cvss3_BaseScore": 9.8,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.9",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "3.8.5",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:netapp:max_data:-",
                "FormattedString": "cpe:2.3:a:netapp:max_data:-:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.7.9": {
            "source": [
                "https://github.com/python/cpython/blob/3.7/Misc/NEWS.d/3.7.9.rst"
            ],
            "BTS": {
                "bpo41304": {
                    "ID": "bpo41304",
                    "url": "https://bugs.python.org/issue41304",
                    "date": "2020-07-15-20-15-08",
                    "nonce": "vNEeYA",
                    "section": "Security"
                }
            }
        },
        "3.8.5": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.5/Misc/NEWS.d/3.8.5.rst"
            ],
            "BTS": {
                "bpo41304": {
                    "ID": "bpo41304",
                    "url": "https://bugs.python.org/issue41304",
                    "date": "2020-07-15-20-15-08",
                    "nonce": "vNEeYA",
                    "section": "Security"
                }
            }
        },
        "3.9.0b5": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.0b5/Misc/NEWS.d/3.9.0b5.rst"
            ],
            "BTS": {
                "bpo41304": {
                    "ID": "bpo41304",
                    "url": "https://bugs.python.org/issue41304",
                    "date": "2020-07-15-20-15-08",
                    "nonce": "vNEeYA",
                    "section": "Security"
                }
            }
        },
        "3.10.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/main/Misc/NEWS.d/3.10.0a1.rst"
            ],
            "BTS": {
                "bpo41304": {
                    "ID": "bpo41304",
                    "url": "https://bugs.python.org/issue41304",
                    "date": "2020-07-15-20-15-08",
                    "nonce": "vNEeYA",
                    "section": "Security"
                }
            }
        }
    }
}