{
    "CVE-ID": "CVE-2008-1721",
    "NVD": {
        "Descriptions": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow.",
        "Cvss2_BaseScore": 7.5,
        "Cvss3_BaseScore": 0,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "Cvss3_VectorString": "",
        "CPEs": [
            {
                "URI": "cpe:/o:debian:debian_linux:4.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:4.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:canonical:ubuntu_linux:8.04::~~-~~~",
                "FormattedString": "cpe:2.3:o:canonical:ubuntu_linux:8.04:*:*:*:-:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:canonical:ubuntu_linux:7.10",
                "FormattedString": "cpe:2.3:o:canonical:ubuntu_linux:7.10:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:canonical:ubuntu_linux:7.04",
                "FormattedString": "cpe:2.3:o:canonical:ubuntu_linux:7.04:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/o:canonical:ubuntu_linux:6.06",
                "FormattedString": "cpe:2.3:o:canonical:ubuntu_linux:6.06:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.4.0",
                "VersionEndExcluding": "2.4.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.5.0",
                "VersionEndExcluding": "",
                "VersionEndIncluding": "2.5.2"
            }
        ]
    },
    "Official": {
        "2.4.6c1": {
            "source": [
                "https://github.com/python/cpython/blob/2.4/Misc/NEWS"
            ],
            "BTS": {
                "bpo2586": {
                    "ID": "bpo2586",
                    "url": "https://bugs.python.org/issue2586",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}