{
    "CVE-ID": "CVE-2022-48565",
    "NVD": {
        "Descriptions": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
        "Cvss2_BaseScore": 0,
        "Cvss3_BaseScore": 9.8,
        "Cvss2_VectorString": "",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "CPEs": [
            {
                "URI": "cpe:/o:debian:debian_linux:10.0",
                "FormattedString": "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "3.6.13",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.10",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "3.8.7",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.9.0",
                "VersionEndExcluding": "3.9.1",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.6.13": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/NEWS.d/3.6.13.rst"
            ],
            "BTS": {
                "bpo42051": {
                    "ID": "bpo42051",
                    "url": "https://bugs.python.org/issue42051",
                    "date": "2020-10-19-10-56-27",
                    "nonce": "EU_B7u",
                    "section": "Security"
                }
            }
        },
        "3.7.10": {
            "source": [
                "https://github.com/python/cpython/blob/3.7/Misc/NEWS.d/3.7.10.rst"
            ],
            "BTS": {
                "bpo42051": {
                    "ID": "bpo42051",
                    "url": "https://bugs.python.org/issue42051",
                    "date": "2020-10-19-10-56-27",
                    "nonce": "EU_B7u",
                    "section": "Security"
                }
            }
        },
        "3.8.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.8.7rc1/Misc/NEWS.d/3.8.7rc1.rst"
            ],
            "BTS": {
                "bpo42051": {
                    "ID": "bpo42051",
                    "url": "https://bugs.python.org/issue42051",
                    "date": "2020-10-19-10-56-27",
                    "nonce": "EU_B7u",
                    "section": "Security"
                }
            }
        },
        "3.9.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.8/Misc/NEWS.d/3.9.1rc1.rst"
            ],
            "BTS": {
                "bpo42051": {
                    "ID": "bpo42051",
                    "url": "https://bugs.python.org/issue42051",
                    "date": "2020-10-19-10-56-27",
                    "nonce": "EU_B7u",
                    "section": "Security"
                }
            }
        },
        "3.10.0a2": {
            "source": [
                "https://github.com/python/cpython/blob/v3.14.0a1/Misc/NEWS.d/3.10.0a2.rst"
            ],
            "BTS": {
                "bpo42051": {
                    "ID": "bpo42051",
                    "url": "https://bugs.python.org/issue42051",
                    "date": "2020-10-19-10-56-27",
                    "nonce": "EU_B7u",
                    "section": "Security"
                }
            }
        }
    }
}