{
    "CVE-ID": "CVE-2010-2089",
    "NVD": {
        "Descriptions": "The audioop module in Python 2.7 and 3.2 does not verify the relationships between size arguments and byte string lengths, which allows context-dependent attackers to cause a denial of service (memory corruption and application crash) via crafted arguments, as demonstrated by a call to audioop.reverse with a one-byte string, a different vulnerability than CVE-2010-1634.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 0,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python:3.2",
                "FormattedString": "cpe:2.3:a:python:python:3.2:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.7": {
            "source": [
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.rst",
                "https://github.com/python/cpython/blob/legacy-trunk/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "8093",
                    "nonce": "cDxsD2",
                    "section": "Library"
                }
            }
        },
        "2.5.6c1": {
            "source": [
                "https://github.com/python/cpython/blob/2.5/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.5.5": {
            "source": [
                "https://github.com/python/cpython/blob/2.5/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.5.5c2": {
            "source": [
                "https://github.com/python/cpython/blob/2.5/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.6.6rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.6/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.1.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.1/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.2a1": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo7673": {
                    "ID": "bpo7673",
                    "url": "https://bugs.python.org/issue7673",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}