{
    "CVE-ID": "CVE-2013-1753",
    "NVD": {
        "Descriptions": "The gzip_decode function in the xmlrpc client library in Python 3.4 and earlier allows remote attackers to cause a denial of service (memory consumption) via a crafted HTTP request.",
        "Cvss2_BaseScore": 5,
        "Cvss3_BaseScore": 7.5,
        "Cvss2_VectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.2.0",
                "VersionEndExcluding": "3.2.6",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.4.0",
                "VersionEndExcluding": "3.4.3",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "2.7.0",
                "VersionEndExcluding": "2.7.9",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.3.0",
                "VersionEndExcluding": "3.3.6",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.2.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043"
                }
            }
        },
        "3.4.3": {
            "source": [
                "https://github.com/python/cpython/blob/3.6/Misc/HISTORY",
                "https://github.com/python/cpython/blob/3.4/Misc/NEWS.d/3.4.3.rst"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043",
                    "date": "9668",
                    "nonce": "TGIC7t",
                    "section": "Library"
                }
            }
        },
        "2.7.9": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.9/Misc/NEWS",
                "https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.9.rst"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043",
                    "date": "9493",
                    "nonce": "TGIC7t",
                    "section": "Library"
                }
            }
        },
        "3.4.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.4.3rc1/Misc/NEWS"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043"
                }
            }
        },
        "3.5a1": {
            "source": [
                "https://github.com/python/cpython/blob/v3.5.0a1/Misc/NEWS"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043"
                }
            }
        },
        "3.3.6": {
            "source": [
                "https://github.com/python/cpython/blob/3.3/Misc/NEWS.d/3.3.6.rst"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043",
                    "date": "9960",
                    "nonce": "TGIC7t",
                    "section": "Library"
                }
            }
        },
        "3.5.0a1": {
            "source": [
                "https://github.com/python/cpython/blob/3.5/Misc/NEWS.d/3.5.0a1.rst"
            ],
            "BTS": {
                "16043": {
                    "ID": "16043",
                    "url": "https://bugs.python.org/issue16043",
                    "date": "8818",
                    "nonce": "TGIC7t",
                    "section": "Library"
                }
            }
        }
    }
}