{
    "CVE-ID": "CVE-2016-3189",
    "NVD": {
        "Descriptions": "Use-after-free vulnerability in bzip2recover in bzip2 1.0.6 allows remote attackers to cause a denial of service (crash) via a crafted bzip2 file, related to block ends set to before the start of the block.",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 6.5,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.10.0",
                "VersionEndExcluding": "3.10.3",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.7.0",
                "VersionEndExcluding": "3.7.13",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.8.0",
                "VersionEndExcluding": "3.8.13",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python",
                "FormattedString": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "3.9.0",
                "VersionEndExcluding": "3.9.11",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:bzip:bzip2:1.0.6",
                "FormattedString": "cpe:2.3:a:bzip:bzip2:1.0.6:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "3.7.13": {
            "source": [
                "https://github.com/python/cpython/blob/3.7/Misc/NEWS.d/3.7.13.rst"
            ],
            "BTS": {
                "bpo44549": {
                    "ID": "bpo44549",
                    "url": "https://bugs.python.org/issue44549",
                    "date": "2022-03-07-17-46-40",
                    "nonce": "SPrGS9",
                    "section": "Windows"
                }
            }
        },
        "3.8.13": {
            "source": [
                "https://github.com/python/cpython/blob/3.8/Misc/NEWS.d/3.8.13.rst"
            ],
            "BTS": {
                "bpo44549": {
                    "ID": "bpo44549",
                    "url": "https://bugs.python.org/issue44549",
                    "date": "2022-03-07-17-46-40",
                    "nonce": "SPrGS9",
                    "section": "Windows"
                }
            }
        },
        "3.9.11": {
            "source": [
                "https://github.com/python/cpython/blob/v3.9.11/Misc/NEWS.d/3.9.11.rst"
            ],
            "BTS": {
                "bpo44549": {
                    "ID": "bpo44549",
                    "url": "https://bugs.python.org/issue44549",
                    "date": "2022-03-07-17-46-40",
                    "nonce": "SPrGS9",
                    "section": "Windows"
                }
            }
        },
        "3.10.3": {
            "source": [
                "https://github.com/python/cpython/blob/v3.10.3/Misc/NEWS.d/3.10.3.rst"
            ],
            "BTS": {
                "bpo44549": {
                    "ID": "bpo44549",
                    "url": "https://bugs.python.org/issue44549",
                    "date": "2022-03-07-17-46-40",
                    "nonce": "SPrGS9",
                    "section": "Windows"
                }
            }
        },
        "3.11.0a7": {
            "source": [
                "https://github.com/python/cpython/blob/v3.13.0a4/Misc/NEWS.d/3.11.0a7.rst"
            ],
            "BTS": {
                "bpo44549": {
                    "ID": "bpo44549",
                    "url": "https://bugs.python.org/issue44549",
                    "date": "2022-03-07-17-46-40",
                    "nonce": "SPrGS9",
                    "section": "Windows"
                }
            }
        }
    }
}