{
    "CVE-ID": "CVE-2010-3493",
    "NVD": {
        "Descriptions": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492.",
        "Cvss2_BaseScore": 4.3,
        "Cvss3_BaseScore": 0,
        "Cvss2_VectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
        "Cvss3_VectorString": "",
        "CPEs": [
            {
                "URI": "cpe:/a:python:python:3.2:alpha",
                "FormattedString": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            },
            {
                "URI": "cpe:/a:python:python:3.1",
                "FormattedString": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*",
                "VersionStartExcluding": "",
                "VersionStartIncluding": "",
                "VersionEndExcluding": "",
                "VersionEndIncluding": ""
            }
        ]
    },
    "Official": {
        "2.6.7rc1": {
            "source": [
                "https://github.com/python/cpython/blob/2.6/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.6.6": {
            "source": [
                "https://github.com/python/cpython/blob/2.6/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.6.6rc2": {
            "source": [
                "https://github.com/python/cpython/blob/2.6/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.1.3rc1": {
            "source": [
                "https://github.com/python/cpython/blob/3.1/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                },
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.2a2": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "2.7.1rc1": {
            "source": [
                "https://github.com/python/cpython/blob/v2.7.1rc1/Misc/NEWS"
            ],
            "BTS": {
                "bpo9129": {
                    "ID": "bpo9129",
                    "url": "https://bugs.python.org/issue9129",
                    "date": "",
                    "nonce": "",
                    "section": ""
                },
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        },
        "3.2a3": {
            "source": [
                "https://github.com/python/cpython/blob/3.2/Misc/NEWS"
            ],
            "BTS": {
                "bpo6706": {
                    "ID": "bpo6706",
                    "url": "https://bugs.python.org/issue6706",
                    "date": "",
                    "nonce": "",
                    "section": ""
                }
            }
        }
    }
}